routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index')->name('welcome');
Route::get('/education', 'PagesController@education')->name('education');
Route::get('/home', 'PagesController@home')->name('home');
Route::get('/experience', 'PagesController@experience')->name('experience');
Route::get('/future', 'PagesController@future')->name('future');
Route::get('/incoming-class', 'PagesController@gallery')->name('gallery');
Route::get('/contest', 'PagesController@contest')->name('contest');

Route::get('begin/{ref?}', 'WizardController@index');
Route::post('begin', 'WizardController@store');
Route::post('uploads', 'UploadsController@store');
Route::get('submission/{ref}', 'PosterPreviewsController@show');

Route::middleware(['web', 'auth'])
    ->prefix('dashboard')
    ->name('dashboard.')
    ->group(function () {
        Route::resource('posters', 'PostersController')->only('index', 'update', 'edit');
        Route::put('approve/{submission}', 'Posters\AddToFeed')->name('poster.approve');
        Route::put('remove/{submission}', 'Posters\RemoveFromFeed')->name('poster.remove');
        Route::delete('deny/{submission}', 'Posters\DeleteEntry')->name('poster.deny');
    });

app/Poster.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Poster extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Posters/AddToFeed.php
<?php

namespace App\Http\Controllers\Posters;

use App\Http\Controllers\Controller;
use App\Submission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AddToFeed extends Controller
{
    public function __invoke(Request $request, Submission $submission)
    {
        $submission->approved_by = Auth::id();
        $submission->save();
    }
}

app/Http/Controllers/Posters/DeleteEntry.php
<?php

namespace App\Http\Controllers\Posters;

use App\Http\Controllers\Controller;
use App\Submission;
use Illuminate\Http\Request;

class DeleteEntry extends Controller
{
    public function __invoke(Submission $submission)
    {
        $submission->delete();
    }
}

app/Http/Controllers/Posters/RemoveFromFeed.php
<?php

namespace App\Http\Controllers\Posters;

use App\Http\Controllers\Controller;
use App\Submission;
use Illuminate\Http\Request;

class RemoveFromFeed extends Controller
{
    public function __invoke(Request $request, Submission $submission)
    {
        $submission->approved_by = null;
        $submission->save();
    }
}

app/Http/Controllers/PostersController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\CountryList;
use App\Helpers\FrameStyle1;
use App\Helpers\ProgramList;
use App\Submission;
use Illuminate\Http\Request;

class PostersController extends Controller
{
    public function index()
    {
        $completed = Submission::where('is_complete', true)->get();
        $incomplete = Submission::where('is_complete', false)->get();

        return view('posters.index', compact('completed', 'incomplete'));
    }

    public function edit(Submission $poster)
    {
        $countries = CountryList::getList();
        $grads = ProgramList::getGraduate();
        $undergrads = ProgramList::getUnderGraduates();

        $frames = [
            'incoming-class-of-2022',
            'my-dream',
            'thunderwolf-4-life',
            'thunderwolves-for-life',
            'pennant-and-flag',
        ];

        return view('posters.edit', [
            'submission' => $poster,
            'countries' => $countries,
            'grads' => $grads,
            'undergrads' => $undergrads,
            'frames' => $frames,
        ]);
    }

    public function update(Request $request, Submission $poster)
    {
        $poster->update([
            'first' => $request->input('firstname'),
            'last' => $request->input('lastname'),
            'email' => $request->input('emailaddress'),
            'choice' => $request->input('framechoice'),
            'country' => $request->input('country'),
            'hometown' => $request->input('hometown'),
            'student_id' => $request->input('student_id'),
            'level_of_study' => $request->input('study'),
            'program' => $request->input('program'),
            'location_details' => $request->input('location_story'),
            'location' => $request->input('location'),
            'posx' => round($request->input('posx')),
            'posy' => round($request->input('posy')),
            'poswidth' => round($request->input('poswidth')),
            'posheight' => round($request->input('posheight')),
            'frame' => $request->input('frame'),
        ]);

        $submission = Submission::find($poster->id);

        $filename = new FrameStyle1($submission);

        $submission->finalphoto = $filename->filename;
        $submission->is_complete = true;
        $submission->save();

        return redirect()
            ->route('dashboard.posters.index');
    }
}

resources/views/posters/edit.blade.php
@extends('rapture::layouts.dashboard')

@section('title', __('posters.plural'))

@section('content')
    @heading
        @lang('posters.plural')
    @endheading

    @statuses

    <form action="{{ route('dashboard.posters.update', $submission) }}" method="post" data-url="{{ url('') }}">
        @method('PUT')
        @csrf

        <input type="hidden" name="photo" value="{{ !is_null($submission->photo) ? $submission->photo : '' }}">

        <div class="hidden-fields"></div>

        <div class="container">
            <div class="box">
                <div class="poster-edit-screen">
                    <div class="form">
                        <h3>Step 1</h3>
                        <div class="form-field">
                            <label for="firstname">First Name</label>
                            <input type="text" name="firstname" id="firstname" value="{{ old('first', $submission->first) }}">
                        </div>
                        <div class="form-field">
                            <label for="lastname">Last Name</label>
                            <input type="text" name="lastname" id="lastname" value="{{ old('last', $submission->last) }}">
                        </div>
                        <div class="form-field">
                            <label for="email">Email</label>
                            <input type="email" name="emailaddress" id="email" value="{{ old('email', $submission->email) }}">
                        </div>
                        <div class="form-field choice">
                            <label for="story">Mindset</label>
                            <select name="framechoice">
                                <option value="choice"{{ old('framechoice', $submission ? $submission->choice : '') === 'choice' ? ' selected' : '' }}>Choice</option>
                                <option value="dream"{{ old('framechoice', $submission ? $submission->choice : '') === 'dream' ? ' selected' : '' }}>Dream</option>
                                <option value="education"{{ old('framechoice', $submission ? $submission->choice : '') === 'education' ? ' selected' : '' }}>Education</option>
                                <option value="journey"{{ old('framechoice', $submission ? $submission->choice : '') === 'journey' ? ' selected' : '' }}>Journey</option>
                                <option value="voice"{{ old('framechoice', $submission ? $submission->choice : '') === 'voice' ? ' selected' : '' }}>Voice</option>
                                <option value="curiosity"{{ old('framechoice', $submission ? $submission->choice : '') === 'curiosity' ? ' selected' : '' }}>Curiosity</option>
                                <option value="experience"{{ old('framechoice', $submission ? $submission->choice : '') === 'experience' ? ' selected' : '' }}>Experience</option>
                                <option value="home"{{ old('framechoice', $submission ? $submission->choice : '') === 'home' ? ' selected' : '' }}>Home</option>
                                <option value="family"{{ old('framechoice', $submission ? $submission->choice : '') === 'family' ? ' selected' : '' }}>Family</option>
                                <option value="culture"{{ old('framechoice', $submission ? $submission->choice : '') === 'culture' ? ' selected' : '' }}>Culture</option>
                                <option value="community"{{ old('framechoice', $submission ? $submission->choice : '') === 'community' ? ' selected' : '' }}>Community</option>
                                <option value="wellness"{{ old('framechoice', $submission ? $submission->choice : '') === 'wellness' ? ' selected' : '' }}>Wellness</option>
                                <option value="food"{{ old('framechoice', $submission ? $submission->choice : '') === 'food' ? ' selected' : '' }}>Food</option>
                                <option value="comfort"{{ old('framechoice', $submission ? $submission->choice : '') === 'comfort' ? ' selected' : '' }}>Comfort</option>
                                <option value="spirit"{{ old('framechoice', $submission ? $submission->choice : '') === 'spirit' ? ' selected' : '' }}>Spirit</option>
                                <option value="dream"{{ old('framechoice', $submission ? $submission->choice : '') === 'dream' ? ' selected' : '' }}>Dream</option>
                                <option value="dedication"{{ old('framechoice', $submission ? $submission->choice : '') === 'dedication' ? ' selected' : '' }}>Dedication</option>
                                <option value="career"{{ old('framechoice', $submission ? $submission->choice : '') === 'career' ? ' selected' : '' }}>Career</option>
                                <option value="success"{{ old('framechoice', $submission ? $submission->choice : '') === 'success' ? ' selected' : '' }}>Success</option>
                            </select>
                        </div>
                    </div>
                    <div class="form">
                        <h3>Step 2</h3>
                        <div class="form-field">
                            <label for="">Country</label>
                            <select name="country">
                                @foreach ($countries as $key => $name)
                                    <option value="{{ $key }}"{{ old('country', $submission->country) === $key ? ' selected' : '' }}>{{ $name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-field">
                            <label for="">Hometown</label>
                            <input type="text" name="hometown" value="{{ old('hometown', $submission->hometown) }}">
                        </div>
                        <div class="form-field">
                            <label for="">Lakehead Student ID</label>
                            <input type="text" name="student_id" value="{{ old('student_id', $submission->student_id) }}">
                        </div>
                        <div class="form-field">
                            <label for="study">Level of Study</label>
                            <select name="study" id="study" class="study-level">
                                <option value="undergraduate"{{ old('study', $submission->level_of_study) === 'undergraduate' ? ' selected' : '' }}>Undergraduate (Bachelor)</option>
                                <option value="graduate"{{ old('study', $submission->level_of_study) === 'graduate' ? ' selected' : '' }}>Graduate (Masters/PhD)</option>
                            </select>
                        </div>
                        <div class="form-field">
                            <label for="">Program</label>
                            <select name="program">
                                <optgroup label="Undergraduate">
                                    @foreach ($undergrads as $program)
                                        <option{{ old('program_undergrad', $submission->program) === $program ? ' selected' : '' }}>{{ $program }}</option>
                                    @endforeach
                                </optgroup>
                                <optgroup label="Graduate">
                                    @foreach ($grads as $program)
                                        <option{{ old('program_grad', $submission->program) === $program ? ' selected' : '' }}>{{ $program }}</option>
                                    @endforeach
                                </optgroup>
                            </select>
                        </div>
                    </div>
                    <div class="form">
                        <h3>Step 3</h3>
                        <div class="form-field">
                            <label for="story">Location</label>
                            <textarea name="location">{{ old('location', $submission->location) }}</textarea>
                        </div>
                        <div class="form-field">
                            <label for="story">Location Story</label>
                            <textarea name="location_story">{{ old('location_story', $submission->location_details) }}</textarea>
                        </div>

                        <input type="hidden" name="posx" value="{{ old('posx', $submission->posx) }}">
                        <input type="hidden" name="posy" value="{{ old('posy', $submission->posy) }}">
                        <input type="hidden" name="poswidth" value="{{ old('poswidth', $submission->poswidth) }}">
                        <input type="hidden" name="posheight" value="{{ old('posheight', $submission->posheight) }}">
                    </div>
                </div>

                <button type="submit" class="btn">Save Changes</button>
            </div>

            <div class="box">
                <h3 style="margin-top: 0;">Frame Selection</h3>
                <div class="frames">
                    @foreach ($frames as $frame)
                        <label for="frame{{ $loop->index }}" class="{{ old('frame', $submission ? $submission->frame : '') === $frame ? 'active' : '' }}">
                            <input type="radio" name="frame" id="frame{{ $loop->index }}" value="{{ $frame }}"{{ old('frame', $submission ? $submission->frame : '') === $frame ? 'checked' : '' }}>
                            <img src="{{ asset('img/frames/thumbs/' . $frame . '.jpg') }}" alt="">
                        </label>
                    @endforeach

                    <label for="frame-choice" class="{{ old('frame', $submission ? $submission->frame : '') === 'choice' ? 'active' : '' }}">
                        <input type="radio" name="frame" id="frame-choice" value="choice"{{ old('frame', $submission ? $submission->frame : '') === 'choice' ? 'checked' : '' }}>
                        <img src="{{ asset('img/frames/thumbs/my-' . old('framechoice', $submission ? $submission->choice : 'choice') . '-matters.jpg') }}" id="frame-choice-img" alt="" data-url="{{ asset('img/frames/thumbs/') }}">
                    </label>
                </div>

                <button type="submit" class="btn">Save Changes</button>
            </div>

            <div class="box">
                <div class="crop-box">
                    <div class="crop-holder">
                        <div class="crop-utility">
                            <img src="{{ old('photo', $submission->originalfile) }}" alt="">
                        </div>
                    </div>

                    <div class="preview">
                        <div class="poster-preview">
                            <div class="poster-image">
                                <img src="{{ old('photo', $submission->originalfile) }}">
                            </div>
                            <div class="poster-frame">
                                <img src="{{ url('/img/frames/' . old('frame', $submission->frame()) . '.png') }}">
                            </div>
                        </div>

                        <div style="text-align: center; margin-top: 1.5rem;">
                            <a href="{{ $submission->originalfile }}" class="btn" target="_blank">Raw Image</a>
                        </div>
                    </div>
                </div>

                <button type="submit" class="btn">Save Changes</button>
            </div>
        </div>
    </form>
@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('css/cropper.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('css/dashboard.css?20190515') }}">
@endpush

@push('scripts')
    <script type="text/javascript" src="{{ asset('js/cropper.min.js') }}"></script>
    <script src="{{ asset('js/dashboard.js') }}"></script>
@endpush

resources/views/posters/index.blade.php
@extends('rapture::layouts.dashboard')

@section('title', __('posters.plural'))

@section('content')
    @heading
        @lang('posters.plural')
    @endheading

    <div class="section-header">
        <ul class="tab-headings">
            <li class="tab active"><a href="#complete">Complete</a></li>
            <li class="tab"><a href="#incomplete">Incomplete</a></li>
        </ul>
    </div>

    @statuses

    <div class="container">
        <div class="tab-panel active" id="complete">
            <div class="poster-list">
                @foreach ($completed as $poster)
                    <div class="poster-item">
                        <a href="{{ route('dashboard.posters.edit', $poster) }}" class="edit-poster">
                            <em class="far fa-pen"></em>
                        </a>
                        <a href="{{ url('submission/' . $poster->ref) }}" target="_blank">
                            <img src="{{ asset('storage/' . $poster->finalphoto) }}" alt="">
                        </a>
                        <div class="poster-details">
                            Submitted By
                            <br>
                            <strong><a href="mailto:{{ $poster->email }}">{{ $poster->first }} {{ $poster->last }} <em class="far fa-paper-plane"></em></a></strong>
                            <br><br>
                            Email
                            <br>
                            <strong>{{ $poster->email }}</strong>
                            <br><br>
                            Program
                            <br>
                            <strong>{{ $poster->program }}</strong>
                        </div>
                        <div class="poster-status">
                            <button type="button" class="btn accept-poster {{ is_null($poster->approved_by) ? '' : 'hidden' }}" data-url="{{ route('dashboard.poster.approve', $poster) }}">Promote</button>
                            <button type="button" class="btn outline remove-poster {{ is_null($poster->approved_by) ? 'hidden' : '' }}" data-url="{{ route('dashboard.poster.remove', $poster) }}">Demote</button>

                            <button type="button" class="btn danger decline-poster" data-url="{{ route('dashboard.poster.deny', $poster) }}">Delete</button>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
        <div class="tab-panel" id="incomplete">
            <div class="poster-list">
                @foreach ($incomplete as $poster)
                    <div class="poster-item">
                        <a href="{{ route('dashboard.posters.edit', $poster) }}" class="edit-poster">
                            <em class="far fa-pen"></em>
                        </a>
                        <a href="{{ url('submission/' . $poster->ref) }}" target="_blank">
                            <img src="{{ asset('storage/' . $poster->finalphoto) }}" alt="">
                        </a>
                        <div class="poster-details">
                            Submitted By
                            <br>
                            <strong><a href="mailto:{{ $poster->email }}">{{ $poster->first }} {{ $poster->last }} <em class="far fa-paper-plane"></em></a></strong>
                            <br><br>
                            Email
                            <br>
                            <strong>{{ $poster->email }}</strong>
                            <br><br>
                            Program
                            <br>
                            <strong>{{ $poster->program }}</strong>
                        </div>
                        <div class="poster-status">
                            <button type="button" class="btn danger decline-poster" data-url="{{ route('dashboard.poster.deny', $poster->id) }}">Delete</button>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('css/dashboard.css') }}">
@endpush

@push('scripts')
    <script src="{{ asset('js/dashboard.js') }}"></script>
@endpush

resources/views/posters/show.blade.php
@extends('layouts.public')

@section('content')
    @include('layouts.header', [
        'headings' => [
            'Education',
            'Journey',
            'Voice',
            'Dream',
            'Choice',
        ]
    ])

    <div class="share-screen text-center pt-normal pb-normal">
        <div class="container">
            <h1 class="text-blue uppercase title-large">THANK YOU FOR SHARING YOUR LAKEHEAD PRIDE!</h1>
            <p class="text-large">You have been entered into 10 amazing prize draws. Follow our social media channels and check your Lakehead email for winner announcements starting in mid-May with the grand prize announcement on June 1, 2022.</p>

            <ul class="social-icons text-blue">
                <li><a href="https://www.instagram.com/lakeheadinternational/" target="_blank"><em class="fab fa-instagram"></em></a></li>
                <li><a href="https://www.facebook.com/LakeheadInternational/" target="_blank"><em class="fab fa-facebook"></em></a></li>
                <li><a href="https://www.youtube.com/lakeheadinternational" target="_blank"><em class="fab fa-youtube"></em></a></li>
            </ul>

            <img src="{{ asset('storage/' . $submission->finalphoto) }}" alt="" class="poster">

            <div class="mt-6">
                <a href="{{ asset('storage/' . $submission->finalphoto) }}" class="button" target="_blank">
                    <span>Download &amp; Share Your Image</span>
                    <em class="far fa-comments"></em>
                </a>
            </div>
        </div>
    </div>
@endsection